import React, { useMemo, useState } from 'react';
import type { ActivityLog, Customer, Expense, FinancialAccount, FinancialTransaction, Invoice, InvoiceItem, Product, User } from './types';
import { exportProfessionalFullWorkbook } from './services/professionalReportExport';
import { exportProfessionalPdfReport } from './services/professionalPdfReport';

type Role = 'admin' | 'cashier';
type Session = { id: string; username: string; role: Role };
type View = 'dashboard'|'reports'|'summary'|'pos'|'orders'|'invoices'|'products'|'logs'|'returns'|'expenses'|'customers'|'treasury'|'tills'|'users'|'settings';
type SaleRow = { date: string; section: string; description: string; amount: number; invoiceId?: string; source: string };
type SectionSummary = { section: string; sales: number; expenses: number; returns: number; net: number; reviews: number; ratio: number };

const CASH_ID = 'cash-default';
const CUSTODY_ID = 'falafel-manager-custody';
const APP_VERSION = 'matabikh-unified-v3';
const money = (n?: number) => Number(n || 0).toLocaleString('en-US', { maximumFractionDigits: 0 });
const now = () => new Date().toISOString();
const today = () => new Date().toISOString().slice(0, 10);
const isoDate = (d: string) => new Date(`${d}T12:00:00+03:00`).toISOString();
const id = (p: string) => `${p}-${Date.now()}-${Math.random().toString(36).slice(2, 7)}`;

function read<T>(key: string, fallback: T): T { try { const raw = localStorage.getItem(key); return raw ? JSON.parse(raw) as T : fallback; } catch { return fallback; } }
function useStore<T>(key: string, fallback: T) { const [v, setV] = useState<T>(() => read(key, fallback)); const save = (next: T | ((old: T) => T)) => setV(old => { const val = typeof next === 'function' ? (next as (o:T)=>T)(old) : next; localStorage.setItem(key, JSON.stringify(val)); return val; }); return [v, save] as const; }
function section(v?: string) { const x = (v || 'غير مصنف').trim(); if (x.includes('فلافل')) return 'قسم الفلافل'; if (x.includes('فرن')) return 'قسم الفرن'; if (x.includes('مشوي')) return 'قسم المشويات'; if (x.includes('شرقي')) return 'قسم الشرقي'; if (x.includes('غربي')) return 'قسم الغربي'; if (x.includes('طواجن')) return 'طواجن'; if (x.includes('وجبات')) return 'وجبات'; return x; }
function review(notes?: string) { return Boolean(notes && (notes.includes('✔') || notes.includes('❓') || notes.includes('مراجعة'))); }
function lineTotal(i: InvoiceItem) { return (((i.price || 0) - (i.discount || 0) + (i.manualAddition || 0) + (i.modifiers?.reduce((s, m) => s + m.price, 0) || 0)) * (i.quantity || 1)); }

const defaultUsers: User[] = [
  { id: 'admin', username: 'admin', role: 'admin', salt: 'local', passwordHash: 'admin' },
  { id: 'cashier', username: 'cashier', role: 'cashier', salt: 'local', passwordHash: 'cashier' },
];
const defaultAccounts: FinancialAccount[] = [
  { id: CASH_ID, name: 'درج المحل (الخزينة الرئيسية)', type: 'cash' },
  { id: CUSTODY_ID, name: 'عهدة مسؤول قسم الفلافل', type: 'cash' },
];
const menu: Array<{key: View; label: string; icon: string; roles: Role[]}> = [
  ['dashboard','لوحة التحكم','📊',['admin']],['reports','التقارير','📈',['admin']],['summary','الملخص المالي','📋',['admin']],['pos','نقطة البيع','🧾',['admin','cashier']],['orders','الطلبات','🧾',['admin','cashier']],['invoices','الفواتير','🧾',['admin','cashier']],['products','الأصناف','📦',['admin']],['logs','سجل النشاط','🕘',['admin']],['returns','طلبات الإرجاع','↩️',['admin']],['expenses','المصروفات','💵',['admin','cashier']],['customers','العملاء','👥',['admin']],['treasury','الخزينة','🏦',['admin']],['tills','تقارير الصناديق','🗂️',['admin']],['users','المستخدمون','👤',['admin']],['settings','الإعدادات','⚙️',['admin']],
].map(([key,label,icon,roles]) => ({ key: key as View, label: label as string, icon: icon as string, roles: roles as Role[] }));

function salesRows(invoices: Invoice[], txs: FinancialTransaction[]): SaleRow[] {
  const rows: SaleRow[] = [];
  invoices.filter(i => i.type !== 'return' && i.paymentStatus === 'paid').forEach(inv => inv.items.forEach(item => rows.push({ date: (inv.paidDate || inv.date).slice(0,10), section: section(item.category), description: item.productName, amount: lineTotal(item), invoiceId: inv.id, source: 'فاتورة' })));
  txs.filter(t => t.type === 'sale_income').forEach(t => { const exists = Boolean(t.relatedInvoiceId) || invoices.some(i => i.id === `manual-inv-${t.id}`); if (!exists) rows.push({ date: t.date.slice(0,10), section: section(t.category), description: t.description, amount: t.amount, source: 'غلة خزينة' }); });
  return rows;
}
function summaries(invoices: Invoice[], expenses: Expense[], txs: FinancialTransaction[]): SectionSummary[] {
  const sr = salesRows(invoices, txs);
  const returns = invoices.filter(i => i.type === 'return').flatMap(inv => inv.items.map(item => ({ section: section(item.category), amount: Math.abs(lineTotal(item)) })));
  const names = Array.from(new Set([...sr.map(r => r.section), ...returns.map(r => r.section), ...expenses.map(e => section(e.category))]));
  return names.map(name => { const sales = sr.filter(r => r.section === name).reduce((s,r)=>s+r.amount,0); const ex = expenses.filter(e => e.status !== 'cancelled' && section(e.category) === name).reduce((s,e)=>s+(e.amount||0),0); const ret = returns.filter(r=>r.section===name).reduce((s,r)=>s+r.amount,0); const rev = expenses.filter(e => section(e.category) === name && (review(e.notes) || !e.amount || e.status === 'needs_review')).length; return { section: name, sales, expenses: ex, returns: ret, net: sales - ex - ret, reviews: rev, ratio: sales > 0 ? ex / sales : ex > 0 ? 999 : 0 }; }).sort((a,b)=>b.net-a.net);
}
function balances(accounts: FinancialAccount[], txs: FinancialTransaction[]) { const map = new Map<string, number>(); accounts.forEach(a=>map.set(a.id,0)); txs.forEach(t => { if(t.fromAccountId) map.set(t.fromAccountId,(map.get(t.fromAccountId)||0)-t.amount); if(t.toAccountId) map.set(t.toAccountId,(map.get(t.toAccountId)||0)+t.amount); }); return map; }
function makeManualInvoice(t: FinancialTransaction): Invoice { return { id:`manual-inv-${t.id}`, date:t.date, paidDate:t.date, type:'sale', status:'completed', paymentStatus:'paid', paymentMethod:'cash', processedBy:'admin', customerInfo:{name:'غلة يدوية / درج المحل', phone:''}, notes:`مولدة من حركة خزينة: ${t.description}`, total:t.amount, items:[{productId:`manual-${t.id}`, productName:t.description, category:section(t.category), price:t.amount, quantity:1, discount:0, manualAddition:0, notes:'غلة يدوية مرتبطة بالتقارير والخزينة'}] }; }

function Card({title,value,tone='slate'}:{title:string;value:string;tone?:'green'|'red'|'blue'|'amber'|'slate'}) { return <div className={`un-card ${tone}`}><span>{title}</span><b>{value}</b></div>; }
function SectionTable({rows}:{rows:SectionSummary[]}) { return <div className="un-panel"><h3>تحليل الأقسام</h3><div className="un-table"><table><thead><tr><th>القسم</th><th>الغلة</th><th>المصروفات</th><th>المرتجعات</th><th>الصافي</th><th>مراجعة</th><th>المؤشر</th></tr></thead><tbody>{rows.map(r=><tr key={r.section}><td>{r.section}</td><td>{money(r.sales)}</td><td>{money(r.expenses)}</td><td>{money(r.returns)}</td><td className={r.net>=0?'ok':'bad'}>{money(r.net)}</td><td>{r.reviews}</td><td>{r.ratio>1?'خطر':r.ratio>.6?'تحذير':r.reviews?'مراجعة':'طبيعي'}</td></tr>)}</tbody></table></div></div>; }

export default function UnifiedApp() {
  const [users,setUsers] = useStore<User[]>('users', defaultUsers);
  const [session,setSession] = useStore<Session|null>('sessionUser', null);
  const [products,setProducts] = useStore<Product[]>('products', []);
  const [invoices,setInvoices] = useStore<Invoice[]>('invoices', []);
  const [expenses,setExpenses] = useStore<Expense[]>('expenses', []);
  const [accounts,setAccounts] = useStore<FinancialAccount[]>('financialAccounts', defaultAccounts);
  const [transactions,setTransactions] = useStore<FinancialTransaction[]>('financialTransactions', []);
  const [customers,setCustomers] = useStore<Customer[]>('customers', []);
  const [logs,setLogs] = useStore<ActivityLog[]>('activityLogs', []);
  const [view,setView] = useState<View>(session?.role === 'cashier' ? 'pos' : 'dashboard');
  const [notice,setNotice] = useState('');
  const [cart,setCart] = useState<InvoiceItem[]>([]);
  const [search,setSearch] = useState('');
  const currentUser = session;
  const sr = useMemo(()=>salesRows(invoices,transactions),[invoices,transactions]);
  const sum = useMemo(()=>summaries(invoices,expenses,transactions),[invoices,expenses,transactions]);
  const bal = useMemo(()=>balances(accounts,transactions),[accounts,transactions]);
  const totals = useMemo(()=>{const sales=sr.reduce((s,r)=>s+r.amount,0); const exp=expenses.filter(e=>e.status!=='cancelled').reduce((s,e)=>s+(e.amount||0),0); const ret=invoices.filter(i=>i.type==='return').reduce((s,i)=>s+Math.abs(i.total),0); return {sales,exp,ret,net:sales-exp-ret,reviews:expenses.filter(e=>review(e.notes)||!e.amount||e.status==='needs_review').length};},[sr,expenses,invoices]);
  const alert = (m:string)=>{setNotice(m); setTimeout(()=>setNotice(''),3000)};
  const log = (operation:string,description:string)=>setLogs(p=>[{id:id('log'), userId:currentUser?.id||'system', username:currentUser?.username||'النظام', operation, description, date:now()},...p].slice(0,5000));
  const sync = () => { const am = new Map(accounts.map(a=>[a.id,a])); defaultAccounts.forEach(a=>am.set(a.id,{...(am.get(a.id)||a),...a})); const im = new Map(invoices.map(i=>[i.id,i])); transactions.filter(t=>t.type==='sale_income'&&!t.relatedInvoiceId).forEach(t=>im.set(`manual-inv-${t.id}`,makeManualInvoice(t))); const tm = new Map(transactions.map(t=>[t.id,t])); expenses.forEach(e=>{ if(e.status==='cancelled')return; const txid=e.linkedTransactionId||`tx-exp-${e.id}`; tm.set(txid,{id:txid,date:e.date,description:e.description,amount:e.amount||0,type:'expense',fromAccountId:e.accountId||CASH_ID,category:section(e.category),relatedExpenseId:e.id}); }); setAccounts(Array.from(am.values())); setInvoices(Array.from(im.values())); setTransactions(Array.from(tm.values())); localStorage.setItem('appVersion',APP_VERSION); log('مزامنة شاملة','إصلاح ربط الفواتير والخزينة والمصروفات'); alert('تمت المزامنة الشاملة'); };
  const addSale = (date:string, cat:string, desc:string, amount:number, items?:InvoiceItem[]) => { const lines=items?.length?items:[{productId:id('manual'),productName:desc,category:cat,price:amount,quantity:1,discount:0,manualAddition:0}]; const total=lines.reduce((s,i)=>s+lineTotal(i),0); const inv:Invoice={id:id('inv'),date:isoDate(date),paidDate:isoDate(date),type:'sale',status:'completed',paymentStatus:'paid',paymentMethod:'cash',processedBy:currentUser?.username||'admin',customerInfo:{name:'غلة يدوية / درج المحل',phone:''},notes:desc,total,items:lines}; const tx:FinancialTransaction={id:id('tx-sale'),date:inv.date,description:desc,amount:total,type:'sale_income',toAccountId:CASH_ID,relatedInvoiceId:inv.id,category:cat}; setInvoices(p=>[...p,inv]); setTransactions(p=>[...p,tx]); log('تسجيل غلة مبيعات',`${cat} - ${desc} - ${money(total)}`); alert('تم تسجيل الغلة كفاتورة وحركة خزينة'); };
  const addExpense = (date:string, cat:string, desc:string, amount:number, notes='مكتمل', accountId=CASH_ID) => { const e:Expense={id:id('exp'),date:isoDate(date),description:desc,amount,category:section(cat),accountId,processedBy:currentUser?.username||'admin',notes,status:review(notes)||amount<=0?'needs_review':'completed',reviewFlag:notes.includes('❓')?'question':notes.includes('✔')?'check':null}; const tx:FinancialTransaction={id:id('tx-exp'),date:e.date,description:desc,amount,type:'expense',fromAccountId:accountId,category:section(cat),relatedExpenseId:e.id}; e.linkedTransactionId=tx.id; setExpenses(p=>[...p,e]); setTransactions(p=>[...p,tx]); log('تسجيل مصروف',`${section(cat)} - ${desc} - ${money(amount)}`); alert('تم تسجيل المصروف وربطه بالخزينة'); };
  const updateExpense = (eid:string, patch:Partial<Expense>) => { setExpenses(p=>p.map(e=>e.id===eid?{...e,...patch,updatedAt:now(),updatedBy:currentUser?.username}:e)); setTransactions(p=>p.map(t=>t.relatedExpenseId===eid?{...t,description:patch.description||t.description,amount:patch.amount??t.amount,category:section(patch.category||t.category)}:t)); log('تعديل مصروف',`تم تعديل ${eid}`); alert('تم تعديل المصروف والخزينة'); };
  const sellCart = (type:'sale'|'dine_in'|'takeaway'='sale') => { if(!cart.length)return alert('السلة فارغة'); const total=cart.reduce((s,i)=>s+lineTotal(i),0); const inv:Invoice={id:id('inv'),date:now(),paidDate:now(),type,status:'completed',paymentStatus:'paid',paymentMethod:'cash',processedBy:currentUser?.username||'cashier',customerInfo:{name:'زبون نقدي',phone:''},total,items:cart}; const tx:FinancialTransaction={id:id('tx-sale'),date:inv.date,description:`إيراد فاتورة ${inv.id}`,amount:total,type:'sale_income',toAccountId:CASH_ID,relatedInvoiceId:inv.id,category:cart[0]?.category||'مبيعات'}; setInvoices(p=>[...p,inv]); setTransactions(p=>[...p,tx]); setCart([]); log('بيع كاشير',`${inv.id} - ${money(total)}`); alert('تم حفظ البيع'); };
  const exportBackup=()=>{const blob=new Blob([JSON.stringify({users,products,invoices,expenses,accounts,transactions,customers,logs,appVersion:APP_VERSION},null,2)],{type:'application/json'}); const a=document.createElement('a'); a.href=URL.createObjectURL(blob); a.download=`matabikh-backup-${today()}.json`; a.click(); URL.revokeObjectURL(a.href);};
  const importBackup=(file?:File)=>{if(!file)return; const r=new FileReader(); r.onload=()=>{const d=JSON.parse(String(r.result||'{}')); if(d.products)setProducts(d.products); if(d.invoices)setInvoices(d.invoices); if(d.expenses)setExpenses(d.expenses); if(d.accounts)setAccounts(d.accounts); if(d.transactions)setTransactions(d.transactions); if(d.customers)setCustomers(d.customers); if(d.logs)setLogs(d.logs); alert('تم الاستيراد');}; r.readAsText(file);};
  const exportExcel=()=>exportProfessionalFullWorkbook(expenses,invoices,transactions,accounts); const exportPdf=()=>exportProfessionalPdfReport(expenses,invoices,transactions,accounts);
  if(!currentUser) return <Login users={users} onLogin={(u,p)=>{const user=users.find(x=>x.username===u&&(x.passwordHash===p||p===x.username)); if(!user)return alert('بيانات الدخول غير صحيحة'); setSession({id:user.id,username:user.username,role:user.role}); setView(user.role==='cashier'?'pos':'dashboard');}} notice={notice}/>;
  return <div dir="rtl" className="unified"><aside><div className="brand"><div className="mark">م</div><div><b>مطابخ الشرق</b><small>نظام موحّد</small></div></div>{menu.filter(m=>m.roles.includes(currentUser.role)).map(m=><button key={m.key} className={view===m.key?'active':''} onClick={()=>setView(m.key)}><span>{m.icon}</span>{m.label}</button>)}<button className="logout" onClick={()=>setSession(null)}>خروج</button></aside><main><header><div><h1>{menu.find(m=>m.key===view)?.label}</h1><p>الفواتير، المبيعات، المصروفات، الخزينة والتقارير مرتبطة من مصدر واحد.</p></div><div className="actions"><button onClick={sync}>مزامنة وإصلاح</button><button onClick={exportExcel}>Excel شامل</button><button onClick={exportPdf}>PDF شامل</button></div></header>{notice&&<div className="toast">{notice}</div>}{render()}</main></div>;
  function render(){ if(view==='dashboard')return <><div className="cards"><Card title="إجمالي الغلة" value={money(totals.sales)} tone="green"/><Card title="إجمالي المصروفات" value={money(totals.exp)} tone="red"/><Card title="صافي التشغيل" value={money(totals.net)} tone={totals.net>=0?'blue':'red'}/><Card title="بنود مراجعة" value={String(totals.reviews)} tone="amber"/></div><SectionTable rows={sum}/><Recent sales={sr} expenses={expenses}/></>; if(view==='reports')return <Reports rows={sum} onExcel={exportExcel} onPdf={exportPdf}/>; if(view==='summary')return <Summary accounts={accounts} bal={bal} rows={sum} totals={totals}/>; if(view==='pos')return <POS products={products} cart={cart} setCart={setCart} search={search} setSearch={setSearch} sell={sellCart}/>; if(view==='orders')return <Invoices title="الطلبات" invoices={invoices.filter(i=>i.status!=='completed')}/>; if(view==='invoices')return <Invoices title="الفواتير" invoices={invoices}/>; if(view==='products')return <Products products={products} setProducts={setProducts}/>; if(view==='logs')return <Logs logs={logs}/>; if(view==='returns')return <Returns invoices={invoices} setInvoices={setInvoices} log={log}/>; if(view==='expenses')return <Expenses expenses={expenses} accounts={accounts} addExpense={addExpense} updateExpense={updateExpense} setExpenses={setExpenses}/>; if(view==='customers')return <Customers customers={customers} setCustomers={setCustomers}/>; if(view==='treasury')return <Treasury accounts={accounts} transactions={transactions} bal={bal} addSale={addSale} addExpense={addExpense} setTransactions={setTransactions}/>; if(view==='tills')return <Tills sales={sr} expenses={expenses}/>; if(view==='users')return <Users users={users} setUsers={setUsers}/>; return <Settings sync={sync} exportBackup={exportBackup} importBackup={importBackup}/>; }
}

function Login({onLogin,notice}:{users:User[];onLogin:(u:string,p:string)=>void;notice:string}){const[u,setU]=useState('admin'),[p,setP]=useState('admin');return <div className="login"><div><h1>مطابخ الشرق</h1><p>admin/admin أو cashier/cashier</p><input value={u} onChange={e=>setU(e.target.value)} placeholder="المستخدم"/><input value={p} type="password" onChange={e=>setP(e.target.value)} placeholder="كلمة المرور"/><button onClick={()=>onLogin(u,p)}>دخول</button>{notice&&<b>{notice}</b>}</div></div>}
function POS({products,cart,setCart,search,setSearch,sell}:{products:Product[];cart:InvoiceItem[];setCart:React.Dispatch<React.SetStateAction<InvoiceItem[]>>;search:string;setSearch:(v:string)=>void;sell:(t?:'sale'|'dine_in'|'takeaway')=>void}){const filtered=products.filter(p=>p.name.includes(search)||section(p.category).includes(search)).slice(0,80);const add=(p:Product)=>setCart(c=>[...c,{productId:p.id,productName:p.name,category:section(p.category),price:p.salePrice||p.price,quantity:1,discount:0}]);return <div className="grid"><section><h3>شاشة الكاشير</h3><input value={search} onChange={e=>setSearch(e.target.value)} placeholder="بحث"/><div className="products">{filtered.map(p=><button key={p.id} onClick={()=>add(p)}><b>{p.name}</b><small>{section(p.category)}</small><strong>{money(p.price)}</strong></button>)}</div></section><section><h3>السلة</h3>{cart.map((i,k)=><div className="line" key={k}><span>{i.productName}</span><input type="number" value={i.quantity} onChange={e=>setCart(c=>c.map((x,j)=>j===k?{...x,quantity:Number(e.target.value)}:x))}/><b>{money(lineTotal(i))}</b><button onClick={()=>setCart(c=>c.filter((_,j)=>j!==k))}>حذف</button></div>)}<h2>الإجمالي {money(cart.reduce((s,i)=>s+lineTotal(i),0))}</h2><button onClick={()=>sell('sale')}>بيع نقدي</button><button onClick={()=>sell('dine_in')}>صالة</button><button onClick={()=>sell('takeaway')}>سفري</button></section></div>}
function Expenses({expenses,accounts,addExpense,updateExpense,setExpenses}:{expenses:Expense[];accounts:FinancialAccount[];addExpense:(d:string,c:string,desc:string,a:number,n?:string,acc?:string)=>void;updateExpense:(id:string,p:Partial<Expense>)=>void;setExpenses:React.Dispatch<React.SetStateAction<Expense[]>>}){const[d,setD]=useState(today()),[c,setC]=useState('قسم الفلافل'),[desc,setDesc]=useState(''),[a,setA]=useState(''),[n,setN]=useState('مكتمل'),[acc,setAcc]=useState(CASH_ID);return <section><div className="split"><h3>المصروفات</h3><button onClick={()=>setExpenses(p=>p.map(e=>({...e,notes:'مكتمل',status:'completed',reviewFlag:null})))}>اعتماد الكل مكتمل</button></div><div className="form"><input type="date" value={d} onChange={e=>setD(e.target.value)}/><input value={c} onChange={e=>setC(e.target.value)} placeholder="القسم"/><input value={desc} onChange={e=>setDesc(e.target.value)} placeholder="البيان"/><input type="number" value={a} onChange={e=>setA(e.target.value)} placeholder="المبلغ"/><select value={n} onChange={e=>setN(e.target.value)}><option>مكتمل</option><option>✔ يحتاج مراجعة</option><option>❓ يحتاج مراجعة</option></select><select value={acc} onChange={e=>setAcc(e.target.value)}>{accounts.map(x=><option key={x.id} value={x.id}>{x.name}</option>)}</select><button onClick={()=>{addExpense(d,c,desc,Number(a),n,acc);setDesc('');setA('')}}>حفظ</button></div><DataTable rows={expenses.slice().reverse().map(e=>({التاريخ:e.date.slice(0,10),القسم:section(e.category),البيان:e.description,المبلغ:money(e.amount),الحالة:review(e.notes)||!e.amount?e.notes||'مراجعة':'مكتمل',إجراء:<button onClick={()=>updateExpense(e.id,{notes:'مكتمل',status:'completed',reviewFlag:null})}>مكتمل</button>}))}/></section>}
function Treasury({accounts,transactions,bal,addSale,addExpense,setTransactions}:{accounts:FinancialAccount[];transactions:FinancialTransaction[];bal:Map<string,number>;addSale:(d:string,c:string,desc:string,a:number)=>void;addExpense:(d:string,c:string,desc:string,a:number,n?:string,acc?:string)=>void;setTransactions:React.Dispatch<React.SetStateAction<FinancialTransaction[]>>}){const[d,setD]=useState(today()),[c,setC]=useState('قسم الفلافل'),[desc,setDesc]=useState(''),[a,setA]=useState('');return <><div className="cards">{accounts.map(x=><Card key={x.id} title={x.name} value={money(bal.get(x.id)||0)} tone="blue"/>)}</div><section><h3>إدخال يدوي</h3><div className="form"><input type="date" value={d} onChange={e=>setD(e.target.value)}/><input value={c} onChange={e=>setC(e.target.value)}/><input value={desc} onChange={e=>setDesc(e.target.value)} placeholder="البيان"/><input type="number" value={a} onChange={e=>setA(e.target.value)}/><button onClick={()=>addSale(d,c,desc||`غلة ${c}`,Number(a))}>تسجيل غلة</button><button onClick={()=>addExpense(d,c,desc||`مصروف ${c}`,Number(a),'مكتمل')}>تسجيل مصروف</button><button onClick={()=>setTransactions(p=>[...p,{id:id('tx-custody'),date:isoDate(d),description:desc||'عهدة مسؤول قسم',amount:Number(a),type:'capital_deposit',toAccountId:CUSTODY_ID,category:c}])}>تسجيل عهدة</button></div></section><DataTable rows={transactions.slice().reverse().map(t=>({التاريخ:t.date.slice(0,10),النوع:t.type,البيان:t.description,القسم:section(t.category),المبلغ:money(t.amount)}))}/></>}
function Reports({rows,onExcel,onPdf}:{rows:SectionSummary[];onExcel:()=>void;onPdf:()=>void}){const max=Math.max(...rows.map(r=>Math.max(r.sales,r.expenses)),1);return <><section><div className="split"><h3>تقرير شامل</h3><div><button onClick={onExcel}>تصدير Excel منسق</button><button onClick={onPdf}>تصدير PDF شامل</button></div></div>{rows.map(r=><div className="bar" key={r.section}><b>{r.section}</b><i><span style={{width:`${Math.max(2,r.sales/max*100)}%`}}/></i><i><em style={{width:`${Math.max(2,r.expenses/max*100)}%`}}/></i><small>غلة {money(r.sales)} / مصروف {money(r.expenses)} / صافي {money(r.net)}</small></div>)}</section><SectionTable rows={rows}/></>}
function Summary({accounts,bal,rows,totals}:{accounts:FinancialAccount[];bal:Map<string,number>;rows:SectionSummary[];totals:any}){return <><div className="cards"><Card title="الغلة" value={money(totals.sales)} tone="green"/><Card title="المصروفات" value={money(totals.exp)} tone="red"/><Card title="الصافي" value={money(totals.net)} tone="blue"/></div><div className="cards">{accounts.map(a=><Card key={a.id} title={a.name} value={money(bal.get(a.id)||0)}/>)}</div><SectionTable rows={rows}/></>}
function Invoices({title,invoices}:{title:string;invoices:Invoice[]}){return <section><h3>{title}</h3><DataTable rows={invoices.slice().reverse().map(i=>({رقم:i.id,التاريخ:i.date.slice(0,10),النوع:i.type,الحالة:i.status,الدفع:i.paymentStatus,الإجمالي:money(i.total),البنود:i.items.map(x=>x.productName).join('، ')}))}/></section>}
function Products({products,setProducts}:{products:Product[];setProducts:React.Dispatch<React.SetStateAction<Product[]>>}){const[n,setN]=useState(''),[c,setC]=useState('قسم الفلافل'),[p,setP]=useState('0');return <section><div className="split"><h3>الأصناف ({products.length})</h3><div className="form"><input value={n} onChange={e=>setN(e.target.value)} placeholder="الصنف"/><input value={c} onChange={e=>setC(e.target.value)}/><input type="number" value={p} onChange={e=>setP(e.target.value)}/><button onClick={()=>{if(n)setProducts(x=>[...x,{id:id('prod'),name:n,category:section(c),price:Number(p),type:'product',isAvailable:true,reviewStatus:Number(p)>0?'ok':'needs_price'}]);}}>إضافة</button></div></div><div className="products">{products.map(x=><div key={x.id}><b>{x.name}</b><small>{section(x.category)}</small><strong>{money(x.price)}</strong></div>)}</div></section>}
function Recent({sales,expenses}:{sales:SaleRow[];expenses:Expense[]}){return <div className="grid"><section><h3>آخر المبيعات</h3>{sales.slice(-10).reverse().map((x,i)=><p key={i}>{x.date} - {x.section} <b>{money(x.amount)}</b></p>)}</section><section><h3>آخر المصروفات</h3>{expenses.slice(-10).reverse().map(x=><p key={x.id}>{x.date.slice(0,10)} - {x.description} <b>{money(x.amount)}</b></p>)}</section></div>}
function Logs({logs}:{logs:ActivityLog[]}){return <section><h3>سجل النشاط</h3>{logs.map(l=><p key={l.id}>{new Date(l.date).toLocaleString('ar-EG')} - <b>{l.operation}</b> - {l.description}</p>)}</section>}
function Returns({invoices,setInvoices,log}:{invoices:Invoice[];setInvoices:React.Dispatch<React.SetStateAction<Invoice[]>>;log:(o:string,d:string)=>void}){return <section><h3>طلبات الإرجاع</h3>{invoices.filter(i=>i.type!=='return').slice(-20).reverse().map(i=><p key={i.id}>{i.id} - {money(i.total)} <button onClick={()=>{const r={...i,id:id('ret'),type:'return' as const,date:now(),total:-Math.abs(i.total),notes:`مرتجع ${i.id}`};setInvoices(p=>[...p,r]);log('مرتجع',r.id)}}>إرجاع كامل</button></p>)}</section>}
function Customers({customers,setCustomers}:{customers:Customer[];setCustomers:React.Dispatch<React.SetStateAction<Customer[]>>}){const[n,setN]=useState(''),[p,setP]=useState('');return <section><div className="form"><input value={n} onChange={e=>setN(e.target.value)} placeholder="الاسم"/><input value={p} onChange={e=>setP(e.target.value)} placeholder="الهاتف"/><button onClick={()=>{if(n)setCustomers(c=>[...c,{id:id('cust'),name:n,phone:p}])}}>إضافة</button></div>{customers.map(c=><p key={c.id}>{c.name} - {c.phone}</p>)}</section>}
function Users({users,setUsers}:{users:User[];setUsers:React.Dispatch<React.SetStateAction<User[]>>}){const[n,setN]=useState(''),[r,setR]=useState<Role>('cashier');return <section><div className="form"><input value={n} onChange={e=>setN(e.target.value)} placeholder="مستخدم"/><select value={r} onChange={e=>setR(e.target.value as Role)}><option value="cashier">كاشير</option><option value="admin">مدير</option></select><button onClick={()=>{if(n)setUsers(u=>[...u,{id:id('user'),username:n,role:r,salt:'local',passwordHash:n}])}}>إضافة</button></div>{users.map(u=><p key={u.id}>{u.username} - {u.role}</p>)}</section>}
function Tills({sales,expenses}:{sales:SaleRow[];expenses:Expense[]}){const days=Array.from(new Set([...sales.map(s=>s.date),...expenses.map(e=>e.date.slice(0,10))])).sort().reverse();return <section><h3>تقارير الصناديق</h3><DataTable rows={days.map(d=>{const s=sales.filter(x=>x.date===d).reduce((a,b)=>a+b.amount,0);const e=expenses.filter(x=>x.date.slice(0,10)===d).reduce((a,b)=>a+(b.amount||0),0);return {اليوم:d,الغلة:money(s),المصروفات:money(e),المتوقع:money(s-e)}})}/></section>}
function Settings({sync,exportBackup,importBackup}:{sync:()=>void;exportBackup:()=>void;importBackup:(f?:File)=>void}){return <section><h3>الإعدادات وإدارة البيانات</h3><button onClick={sync}>مزامنة وإصلاح</button><button onClick={exportBackup}>تصدير نسخة JSON</button><label className="file">استيراد نسخة<input hidden type="file" accept="application/json" onChange={e=>importBackup(e.target.files?.[0])}/></label><button className="danger" onClick={()=>{if(confirm('حذف بيانات هذا المتصفح؟')){localStorage.clear();location.reload()}}}>مسح البيانات المحلية</button><p>يفضل تصدير نسخة قبل المسح. النظام الجديد موحد الحسابات.</p></section>}
function DataTable({rows}:{rows:Array<Record<string,any>>}){if(!rows.length)return <p>لا توجد بيانات.</p>;const cols=Object.keys(rows[0]);return <div className="table"><table><thead><tr>{cols.map(c=><th key={c}>{c}</th>)}</tr></thead><tbody>{rows.map((r,i)=><tr key={i}>{cols.map(c=><td key={c}>{r[c]}</td>)}</tr>)}</tbody></table></div>}
